/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ShoppingMenu;

import static ShoppingMenu.PT.*;
import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        Name2 = new javax.swing.JLabel();
        Name3 = new javax.swing.JLabel();
        Price1 = new javax.swing.JLabel();
        Price2 = new javax.swing.JLabel();
        Price3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        q1 = new javax.swing.JLabel();
        q2 = new javax.swing.JLabel();
        q3 = new javax.swing.JLabel();
        Name4 = new javax.swing.JLabel();
        Name5 = new javax.swing.JLabel();
        Name6 = new javax.swing.JLabel();
        Price4 = new javax.swing.JLabel();
        Price5 = new javax.swing.JLabel();
        Price6 = new javax.swing.JLabel();
        q4 = new javax.swing.JLabel();
        q5 = new javax.swing.JLabel();
        q6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TotalP = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        payTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Bill payment ");

        Name1.setText("null");

        Name2.setText("null");

        Name3.setText("null");

        Price1.setText("0");

        Price2.setText("0");

        Price3.setText("0");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Price");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("qty");

        q1.setText("0");

        q2.setText("0");

        q3.setText("0");

        Name4.setText("null");

        Name5.setText("null");

        Name6.setText("null");

        Price4.setText("0");

        Price5.setText("0");

        Price6.setText("0");

        q4.setText("0");

        q5.setText("0");

        q6.setText("0");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total price =");

        TotalP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TotalP.setText("0");

        payTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(payTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Name1)
                                    .addComponent(Name2)
                                    .addComponent(Name3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Name5)
                                        .addComponent(Name4)
                                        .addComponent(Name6))))
                            .addComponent(jLabel1))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(q4)
                                        .addComponent(q3)
                                        .addComponent(q5)
                                        .addComponent(q6))
                                    .addComponent(q2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(q1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TotalP, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Price2)
                                    .addComponent(Price1)
                                    .addComponent(Price4)
                                    .addComponent(Price3)
                                    .addComponent(Price5)
                                    .addComponent(Price6))
                                .addGap(14, 14, 14))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(Name2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(q1)))
                        .addGap(33, 33, 33)
                        .addComponent(Name3)
                        .addGap(27, 27, 27)
                        .addComponent(Name4)
                        .addGap(28, 28, 28)
                        .addComponent(Name5)
                        .addGap(28, 28, 28)
                        .addComponent(Name6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addComponent(Name1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(q2)
                        .addGap(33, 33, 33)
                        .addComponent(q3)
                        .addGap(27, 27, 27)
                        .addComponent(q4)
                        .addGap(28, 28, 28)
                        .addComponent(q5)
                        .addGap(28, 28, 28)
                        .addComponent(q6))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(Price1)
                        .addGap(29, 29, 29)
                        .addComponent(Price2)
                        .addGap(33, 33, 33)
                        .addComponent(Price3)
                        .addGap(27, 27, 27)
                        .addComponent(Price4)
                        .addGap(28, 28, 28)
                        .addComponent(Price5)
                        .addGap(28, 28, 28)
                        .addComponent(Price6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TotalP))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //            PT pt = new PT();
        //SetTextFromFile
//            GetFileInfo();
        DefaultTableModel del = (DefaultTableModel) payTable.getModel();
        String name_item, price_item, quantity_item;
        double price_item_double = 0;
        double sum_price;
//        int quantity_item,i = 0;
        int quantity_item_int = 0, sum_quantity;
//        int i = 0;
        try {
            File myObj = new File("CartTest.txt");
            Scanner myReader = new Scanner(myObj);
            myReader.useDelimiter("\\|");
            while (myReader.hasNext()) {

                name_item = myReader.next();
                quantity_item = myReader.next();
                price_item = myReader.next();

                quantity_item_int = Integer.parseInt(quantity_item);
                price_item_double = Double.parseDouble(price_item);

                sum_quantity = quantity_item_int;
                sum_price = price_item_double;

                for (int k = 0; k <= payTable.getRowCount(); k++) {
                    if (payTable.getRowCount() == 0) {
                        AddRowToJTable(new Object[]{name_item, quantity_item, price_item});
                        break;
                    } else if (name_item.toString().compareTo(payTable.getValueAt(k, 0).toString()) != 0) {
                        AddRowToJTable(new Object[]{name_item, quantity_item, price_item});
                        break;
                    } //                
                    else {
//                    AddRowToJTable(new Object[]{name_item, quantity_item, price_item});
                        quantity_item_int = Integer.parseInt(quantity_item);
                        price_item_double = Double.parseDouble(price_item);
                        for (int j = 0; j <= payTable.getRowCount(); j++) {
                            if (name_item.toString().compareTo(payTable.getValueAt(j, 0).toString()) == 0) {
                                sum_quantity += Integer.parseInt(payTable.getValueAt(j, 1).toString());
                                sum_price += Double.parseDouble(payTable.getValueAt(j, 2).toString());
                                del.removeRow(j);
                                AddRowToJTable(new Object[]{name_item, sum_quantity, sum_price});
                                break;
                            }
                        }

                        System.out.println("================Test =============");

                        break;
                    }
                }
                System.out.println("================Test =============");
                System.out.println("item : " + name_item + " quantity : " + quantity_item + " price : " + price_item);
            }
            myReader.close();
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }


    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

//    public static void GetFileInfo() {
//        try {
//            File myObj = new File("CartTest.txt");
//            Scanner myReader = new Scanner(myObj);
//            while (myReader.hasNextLine()) {
//                String data = myReader.nextLine();
//                System.out.println("Hello World");
//                System.out.println(data);
//            }
//            myReader.close();
//        } catch (FileNotFoundException e) {
//            System.out.println("An error occurred.");
//            e.printStackTrace();
//        }
//    }
    public static void AddRowToJTable(Object[] dataRow) {
        DefaultTableModel model = (DefaultTableModel) payTable.getModel();
        model.addRow(dataRow);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Name1;
    public static javax.swing.JLabel Name2;
    public static javax.swing.JLabel Name3;
    public static javax.swing.JLabel Name4;
    public static javax.swing.JLabel Name5;
    public static javax.swing.JLabel Name6;
    public static javax.swing.JLabel Price1;
    public static javax.swing.JLabel Price2;
    public static javax.swing.JLabel Price3;
    public static javax.swing.JLabel Price4;
    public static javax.swing.JLabel Price5;
    public static javax.swing.JLabel Price6;
    public static javax.swing.JLabel TotalP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    static javax.swing.JTable payTable;
    public static javax.swing.JLabel q1;
    public static javax.swing.JLabel q2;
    public static javax.swing.JLabel q3;
    public static javax.swing.JLabel q4;
    public static javax.swing.JLabel q5;
    public static javax.swing.JLabel q6;
    // End of variables declaration//GEN-END:variables
}
